#!/bin/bash
#PBS -q batch
#PBS -A MAT049
#PBS -N q0.90_ovl2.5
#PBS -j oe
#PBS -l nodes=4
#PBS -l walltime=02:00:00
#PBS -l gres=atlas1%atlas2

export CRAY_CUDA_MPS=1
source $MODULESHOME/init/bash
module load gromacs/5.1.0

cd $PBS_O_WORKDIR
# Extend the run
aprun -n 1 gmx_mpi grompp -f relax_2.mdp -c relax_1.gro -p confinedBSA.top -o relax_2.tpr
# 8 MPI ranks per node, each one tied to 2 openMP threads
aprun -n 32 -N 8 -d 2 gmx_mpi mdrun -ntomp 2 -gpu_id 00000000 -s relax_2.tpr -deffnm relax_2

